crudapp/urls.py
from django.urls import path
from . import views

app_name = "crudapp"
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('create/', views.product_create, name='product_create'),
    path('<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('<int:pk>/delete/', views.product_delete, name="product_delete")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("products/", include("crudapp.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

crudapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

polls/models.py
import datetime
from django.db import models
from django.contrib import admin
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("data published")

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?"
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

crudapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from django.urls import reverse

# Read all products
def product_list(request):
    products = Product.objects.all()
    return render(request, 'crudapp/product_list.html', {'products': products})

# Create a new product
def product_create(request):
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        price = request.POST['price']
        Product.objects.create(name=name, description=description, price=price)
        return redirect('crudapp:product_list')
    return render(request, 'crudapp/product_form.html')

# Update an existing product
def product_edit(request, id):
    product = get_object_or_404(Product, id=id)
    if request.method == 'POST':
        product.name = request.POST['name']
        product.description = request.POST['description']
        product.price = request.POST['price']
        product.save()
        return redirect('crudapp:product_list')
    return render(request, 'crudapp/product_form.html', {'product': product})

def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.delete()
        return redirect('crudapp:product_list')
    return render(request, 'crudapp/product_confirm_delete.html', {'product': product})

polls/views.py
from django.db.models import F
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
       return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "You didn't select a choice.",
        },)
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

crudapp/templates/crudapp/product_confirm_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Product</title>
</head>

<body>
    <h1>Delete Product</h1>
    <p>Are you sure you want to delete "{{ product.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, Delete</button>
    </form>
    <a href="{% url 'product_list' %}">Cancel</a>
</body>

</html>

crudapp/templates/crudapp/product_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if product %}Edit{% else %}Create{% endif %}Product</title>
</head>

<body>
    <h1>{% if product %}Edit{% else %}Create{% endif %} Product</h1>
    <form method="post">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" value="{{ product.name|default:'' }}">
        <br>
        <label for="description">Description:</label>
        <textarea name="description" id="description">{{ product.description|default:'' }}</textarea>
        <br>
        <label for="price">Price</label>
        <input type="number" id="price" name="price" step="0.01" value="{{ product.price|default:''}}">
        <br>
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'crudapp:product_list' %}">Back to Product List</a>
</body>

</html>

crudapp/templates/crudapp/product_list.html
<!DOCTYPE html>
<html>

<head>
    <title>Products</title>
</head>

<body>
    <h1>Products</h1>
    <a href="{% url 'crudapp:product_create' %}">Add New Product</a>
    <ul>
        {% for product in products %}
        <li>
            {{ product.name }} - ${{ product.price }}
            <a href="{% url 'crudapp:product_edit' product.id %}">Edit</a>
            <form action="{% url 'crudapp:product_delete' product.id %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
        </li>
        {% endfor %}
    </ul>
</body>

</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
</head>

<body>
    <form action="{% url 'polls:vote' question.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>
                    {{ question.question_text }}
                </h1>
            </legend>
            {% if error_message %}<p><strong>
                    {{ error_message }}
                </strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id}}">
            <label for="choice{{ forloop.counter}}">{{choice.choice_text}}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
    <a href="{% url 'polls:index' %}">Go Back</a>
</body>

</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>

<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">
                {{ question.question_text }}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</body>

</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>

</html>